remote_theme: pages-themes/minimal@v0.2.0
title: Monica A. Crowe
description: My coding portfolio
![Portfolio Photo](https://media.licdn.com/dms/image/D5603AQF8WLYF8lQaFg/profile-displayphoto-shrink_800_800/0/1673371364395?e=1679529600&v=beta&t=n7czGswW4MZBxmyGw1fxsOV5z10E6QqX10ZhA_v4ZGY)
